### ISSUE TITLE
Surface Mesh generation ( for 3d point )

### ISSUE THREAD

**Issue by shalinsirwani** [bjaraujo/ENigMA#2]
Please provide example using this file... in c++ ( https://justpaste.it/6cdan ) format x y z

**Comment by vijaiaeroastro** [comment]
Hey @shalinsirwani. What you have is point clouds. I would advice using point cloud library. Here is an example of meshing unordered 3d point clouds. http://www.pointclouds.org/documentation/tutorials/greedy_projection.php#greedy-triangulation

**Comment by shalinsirwani** [comment]
I already tried it..
Result is too slow and also not accurate

**Comment by vijaiaeroastro** [comment]
@shalinsirwani That is the case with Point clouds. You cannot simply obtain a perfect triangulation with random point clouds. 

Here is a latest approach from ETH Zurich where they upsample a point cloud to get a better surface construction.

https://github.com/yifita/3PU
and the paper is https://igl.ethz.ch/projects/3pu/

This is still a very active research area and there is a lot to be done in it.

**Comment by shalinsirwani** [comment]
I will you into this..

I have another problem (below is the link) , if you provide me any help it might be useful for me..
https://github.com/cnr-isti-vclab/meshlab/issues/469

**Comment by vijaiaeroastro** [comment]
I think this is irrelevant to ENigMA. You can close the issue here. If you need help, you can email me personally. I use meshlab rarely however i am not familiar with their underlying API. Its GPL code and i don't use it.
